services:
  redis:
    image: redis
    container_name: redis3
    restart: always
    ports:
      - "6379:6379"

    command: redis-server --save 60 1 --loglevel warning

  backend:
    build: .
    container_name: Maktab
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=True
    depends_on:
      - redis

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - "5000:80"
      - "25:25"
      - "143:143"
    volumes:
      - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev

   
  master:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./core/locust:/mnt/locust

    command: -f /mnt/locust/locustfile.py --master -H http://Maktab:8000  


  worker:
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - ./core:/app
    depends_on:
      - redis
      - backend
    

volumes:
  smtp4dev-data:
