# Generated by Django 3.2.25 on 2024-12-05 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20241125_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_like',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='comment.comments'),
        ),
    ]
