# Generated by Django 3.2.25 on 2024-12-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_alter_comment_like_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='star',
            field=models.IntegerField(default=1),
        ),
    ]
