name: Setup Docker-Compose 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Docker-Compose
      run: |  
            sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose  
            sudo chmod +x /usr/local/bin/docker-compose  
    - name: Run Docker-Compose
      run: docker-compose -f docker-compose-stage.yml up --build -d
    - name: Run Test
      run: docker-compose exec backend sh -c "flake8 && pytest"
