name: Setup Docker-Compose 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Docker-Compose
      run: docker-compose -f docker-compose-stage.yml up --build -d
    - name: Run Test
      run: docker-compose exec backend sh -c "flake8 && pytest"
